services:
  - type: web
    name: activos-corrientes-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py
    plan: free # O el plan que prefieras
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0